### ISSUE TITLE
Dark/Light theme alternative

### ISSUE THREAD

**Issue by djselbeck** [gateship-one/odyssey#10]
Add a bright (light) theme to the application design. 

Needs work on the style xmls to dynamically set background, text color.

**Comment by The0x539** [comment]
What about an AMOLED black theme?

**Comment by djselbeck** [comment]
We don't have any problems with that but only have TFT screens :). Do you mean like really black background and white font?

**Comment by The0x539** [comment]
The important part is the background, and sometimes top/bottom action bars,
being #000000. Whether the text and icons are true white or a light gray is
of low relevance.

**Comment by gnome17** [comment]
We implemented a cool and really dark theme for OLED screens. It is currently in the source repo and tested by us. 

As to bright themes we are not sure if we implement them. We also tested them today and the results were not really promising as it looked not aesthetically. Also our themes are not that dark because of the large amount of color already used for the accents and toolbars.

**Comment by The0x539** [comment]
I can't think of many, if any, music apps that don't have light themes, and
they all look fine. And unless the color is in the background or the UI is
almost entirely content, like in a photo gallery app, background color WILL
be important. The dark theme is really prominent in any of the app's lists,
be it the queue, all songs, or an album.

**Comment by gnome17** [comment]
We investigated the issue further today and cleaned up our xmls files for the themes. It is now possible to select a bright theme for every existing theme (including a new one, obviously not for the OLED :) ). 

We still do not really like the aesthetics and think that music players look better in dark themes ;) but we want to provide as much choice as possible.

The new themes will be available in the next version (1.0.11).

**Comment by gnome17** [comment]
Resolved with 1.0.11.
