### ISSUE TITLE
App new release fails to install

### ISSUE THREAD

**Issue by surferjoeit** [gateship-one/odyssey#100]
Hello,
i have this problem with Odyssey latest release. If i try to update with F-Droid, it forces F-droid to close and don’t install.
In addition, if i manually download the apk file when i try to access the download folder, file manager suddenly closes. I have to manually remove the apk file by connecting device to PC and using PC file manager.

Thanks

**Comment by djselbeck** [comment]
Just tested it with Android 5 and 7 and F-Droid 1.0.1. All test cases worked.

Also F-Droid is out of scope for us, because we don't provide the builds there. They are automatically generated from the source code provided here.

**Comment by surferjoeit** [comment]
The apk file mentioned is downloaded from githup, too. I tried with both builds, F-Droid and yours.

**Comment by djselbeck** [comment]
Probably a problem with your android installation. 

What device, version of android are you using? 

What about some logcat?

**Comment by surferjoeit** [comment]
Wiko ridge 4G, Android 5.0.2
I'm not a developer, so please give me some hints on using logcat.

**Comment by surferjoeit** [comment]
Could it be related to the adaptive icon? I had same problem with another app, and it was related to adaptive icon, i think.

**Comment by djselbeck** [comment]
It is possible. But the icon should only be used on devices with api version 26

**Comment by surferjoeit** [comment]
I have the same problem with other apps, i opened a thread on F-Droid forum.

**Comment by djselbeck** [comment]
There seems to be a bug with android build tools:

https://issuetracker.google.com/issues/64434571

Can you try this apk (built with build tools 27.0.1):

https://owncloud.djselbeck.de/index.php/s/DKLDu2b7nblRe0s

**Comment by surferjoeit** [comment]
It works! Great!
Many thanks
Can i share the information in F-Droid?

Il 13 novembre 2017 19:01:04 CET, Hendrik Borghorst <notifications@github.com> ha scritto:
>There seems to be a bug with android build tools:
>
>https://issuetracker.google.com/issues/64434571
>
>Can you try this apk (built with build tools 27.0.1):
>
>https://owncloud.djselbeck.de/index.php/s/DKLDu2b7nblRe0s
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gateship-one/odyssey/issues/100#issuecomment-344004253

-- 
Inviato dal mio dispositivo Android con K-9 Mail.

**Comment by djselbeck** [comment]
Of course ;) please

**Comment by gnome17** [comment]
A new version that fixes this problem is already released on google play and fdroid.
Thank you surferjoeit for reporting this problem.
