### ISSUE TITLE
Coming back to 'my music' view from 'files' view

### ISSUE THREAD

**Issue by Dnupselina** [gateship-one/odyssey#102]
Hi all

When I am navigating in the 'files' view, it's not possible to come back to the 'my music' view unless I open the 'currently played song' view by swiping up and then tap on the menu icon. That's because the menu icon doesn't show up in the 'files' view, instead it appears only a 'back arrow', and no matter how often I tap it, it stays.
It would be useful, if the 'back arrow' would change to the menu icon, once you arrive at the default directory.

Thanks and excuse me if I put this to the wrong thread or so.

**Comment by gnome17** [comment]
Hey,
thanks for your feedback. If you got to the root folder of your storage volume the arrow should switch back to the menu icon. But you can always reach the navigation drawer even if the menu icon isn't there. Just try get the navigation drawer by a swipe gesture.

**Comment by gnome17** [comment]
Due to inactivity
