### ISSUE TITLE
[FR] sound volume limit

### ISSUE THREAD

**Issue by ka223** [gateship-one/odyssey#104]
A sound volume limit would be nice.
After starting music the (bluetooth) volume is sometimes reset, a volume limit setting would protect ears without the need of another (closed source) app.

**Comment by ildar** [comment]
Try other apps around, e.g A2DP Volume (Manage Bluetooth functions) -
https://f-droid.org/app/a2dp.Vol

**Comment by gnome17** [comment]
Out of scope. The volume is handled by the system and not odyssey.
