### ISSUE TITLE
Restrict odysee to certain folders

### ISSUE THREAD

**Issue by TLHN** [gateship-one/odyssey#106]
Hi,

i think it would be great if it was possivle to tell odyssee to only look for music in certain folders, In my case i have a folder called music on the sd card. I already told odysee to use it as default and to scan db from there. But still it shows whatsapp audio files and call recorder files and all kind of downloaded sound files from different folders.

yes, i could paste ".nomedia" in every unwanted folder but i just think adding only the wanted folders would be a more efficient way for most people.

**Comment by gnome17** [comment]
Duplicate see #87
