### ISSUE TITLE
Play all songs?

### ISSUE THREAD

**Issue by dennisguse** [gateship-one/odyssey#123]
I am at the moment like a DAU, as I cannot figure how to play all songs on my device.
Do I need to create a playlist manually adding all songs?

**Comment by djselbeck** [comment]
Don't worry ;). You have to go to the all tracks tab and then just hit the floating play button in the right bottom corner.

We'll add this to the FAQ ;)

**Comment by faissaloo** [comment]
By default if I select a song from all tracks I believe it should play all songs from that point onwards

**Comment by djselbeck** [comment]
The reason why not all tracks are enqueued are simple performance reasons. For big libraries (around 30000 files) the enqueue procedure just takes a few seconds which is undesirable if one just wants to play one specific song fast.

Also the default behaviour for selecting songs will change with the next version (configurable)

**Comment by faissaloo** [comment]
Instead of attempting to enqueue the entire library at once, enqueue while the song is playing, the only case that would cause you to wait would be if the enqueuing of the immediate next song took longer than the song itself.
