### ISSUE TITLE
Support pre-lollipop environments

### ISSUE THREAD

**Issue by KOLANICH** [gateship-one/odyssey#126]

**Comment by dennisguse** [comment]
Pre-Android 5.X has a market share of less than 17% [1], which will further decrease in the future.
Is this really necessary to support this and invest (spare) time for maintenance?

[1] https://developer.android.com/about/dashboards/index.html

**Comment by djselbeck** [comment]
This will not be implemented, see https://github.com/gateship-one/malp/issues/81#issuecomment-354602575 for an explanation.

**Comment by KOLANICH** [comment]
Thank you for the clarification.
