### ISSUE TITLE
Default action for library tracks: add a "play from" option

### ISSUE THREAD

**Issue by regagain** [gateship-one/odyssey#132]
From the [changelog](https://github.com/gateship-one/odyssey/blob/HEAD/CHANGELOG.md):
> Version: 1.1.12 Tag: release-24 (2018-02-03)
> Default action for library tracks selectable (play song, add song (default), add as next song)

Before 1.1.12, the default behavior was to play the song and then continue playing the album/playlist.
It would be nice to add that behavior as an option.

**Comment by mrshll1001** [comment]
Seconded, seems like pretty standard music player behaviour and it was very confusing to see it changed.

**Comment by djselbeck** [comment]
We will add this with rhe next release. We wanted to add some consitency between MALP and Odyssey .

**Comment by gnome17** [comment]
Hi,
we released a new version of odyssey. 
We add the old behaviour as a new option ("Replace and play from index").
Thanks for your feedback and sorry for the inconvenience.
