### ISSUE TITLE
App name origin

### ISSUE THREAD

**Issue by ZeroPointMax** [gateship-one/odyssey#136]
You asked the Community to solve the name question so here is my try (since I did not find an answer yet): you are a Stargate fan right? Because there is a spaceship in the series that is called Odyssey. There is more evidence for that like: "GATEship", your logo and your other app named "malp". So I guess you found a fellow "gater" :+1:

Gaters gonna gate

**Comment by gnome17** [comment]
Ideed you are correct :-)
But as a small addition even the complete organisation name can be found in one special episode.

**Comment by ildar** [comment]
>
>
>
Atlantis is cool but Universe is really catchy! 😀

**Comment by djselbeck** [comment]
> Atlantis is cool but Universe is really catchy! grinning

Good joke

**Comment by ZeroPointMax** [comment]
I like Atlantis best, but SG-1 is also cool. Of course, SG-U is also okay but i like the other ones more.
