### ISSUE TITLE
New Logo/Icon proposal for Odyssey

### ISSUE THREAD

**Issue by mutluhn** [gateship-one/odyssey#141]
![isdnruwpvjqz3d0esnwv](https://user-images.githubusercontent.com/35154172/37598211-b1603b42-2b92-11e8-8360-7bb309c415bb.png)

I made a logo for Odyssey.
All files are available here.

Dropbox [HERE](https://www.dropbox.com/sh/vjtc72ia0id9iqf/AAAF5--HmC5zbVLv6b94glRma?dl=0)

**Comment by djselbeck** [comment]
We do not plan to change the current logo. You should not have invested so much time without contacting us first. I'm sorry 😉
