### ISSUE TITLE
Artist/album cover download does not work

### ISSUE THREAD

**Issue by mikemaikaefer** [gateship-one/odyssey#142]
The automatic download of artist images/album covers is a really cool feature but it does not work properly:

- after first time usage of Odyssey player in WLAN it worked properly, a lot of images have been downloaded

- then I started the player while I have been in mobile network: all previously downloaded images have been lost (I don't know if it is intended to store them or if they would have to be downloaded newly every time - store them would be a really good idea)

- next time in WLAN the imaged did not come back, for some reason they have not been downloaded again

- cover-images that are stored as ID3 in the played FLAC files or which are located as separate image files in album folders also are not shown

**Comment by gnome17** [comment]
Hi,
thanks for your feedback. 
By default odyssey will download and store covers only if you are connected to a WLAN. You can change this in the settings. Your problem never occured to us. Could you provide more information and is this behaviour reproducible so do you loose downloaded covers each time you are not connected to a WLAN?

And regarding your last point:
By default we are using the cover images that are stored by the android media database. If there is no cover we try to download one or use an already downloaded image. Other options are currently not supported but there is already an open issue for that #99.

**Comment by mikemaikaefer** [comment]
Sorry, no more infos for you - I gave up using this player due to too much other bugs (when playing a song from the middle of the album after this song replaying started with the first song of the album instead of the next one, large gaps between two songs which result in drop-outs for albums where songs fade into each other,...)
