### ISSUE TITLE
[FR] Timer stops player

### ISSUE THREAD

**Issue by Florian131985** [gateship-one/odyssey#149]
It would be beneficial to be able to set a timer, which stops the player after a defined period of time.

I am thinking about following user story:
As an audio book listener falling asleep during listening, before playing a playlist or track I can set a time period after which the audio player automatically stops, to be able to find easier the track and position when I stopped listening and to prevent the device to wear out the battery.

**Comment by gnome17** [comment]
Hi,
thanks for your feedback. I already thought about such a feature myself. So we will consider this request but currently we have not much time left for this project so don't except this feature in the near future ;)

**Comment by gnome17** [comment]
Hi,
we just released a new version of odyssey which now includes a sleep timer that is accessible by the overflow menu of the current playlist view.

Should be already available via google play and should be avaible at fdroid in the next week I guess.
