### ISSUE TITLE
Frequently Asked Question (FAQ) Proposal 

### ISSUE THREAD

**Issue by olayhemy** [gateship-one/odyssey#150]
Hello there, I'd like to contribute to your awesome project by writing a Frequent Asked Questions for users self-service. Would love to hear from you, thanks.

**Comment by djselbeck** [comment]
Thanks for your interest in improving this application. However we already have a [FAQ](https://github.com/gateship-one/odyssey/wiki/FAQ). If you like, you can improve it.

I've no idea how github handles write permissions.
