### ISSUE TITLE
Propose New logo

### ISSUE THREAD

**Issue by anaufalm** [gateship-one/odyssey#161]
Hi, check out my blog here. I made a logo for your app. If you like it, I will send the file to you. :)

![](https://steemitimages.com/0x0/https://res.cloudinary.com/hpiynhbhq/image/upload/v1521039999/xjkml8rsulpwvzzvhq6h.png)

https://steemit.com/utopian-io/@naufal/new-icon-logo-design-for-odyssey-music-player

**Comment by gnome17** [comment]
As said in other issues and already in the FAQ we ignore everything from Utopian.io and we won't accept another icon.
