### ISSUE TITLE
[FR] Delete a track/album from Odyssey

### ISSUE THREAD

**Issue by geopipo** [gateship-one/odyssey#163]
Music files can be stored in different directories on a smartphone, like download, music, specific folders etc… Odyssey aggregate all the files letting us the possibility to play everything from one interface, wich is pretty cool. It would be nice to also have the possibility to delete files from the music player.

**Comment by gnome17** [comment]
Hi,
thanks for your feedback. 

As stated in #71 we have no intention to add such an option.
