### ISSUE TITLE
[FR] recent albums

### ISSUE THREAD

**Issue by ildar** [gateship-one/odyssey#17]
As in Apollo

**Comment by gnome17** [comment]
Thanks for your feedback, we are currently in the process of merging our artwork support in the master branch to add the ability to download artwork from the internet. After this we'll check your request.

**Comment by gnome17** [comment]
It took a while but its finally implemented with this commit f89e7d2. It is available from the options menu in the albums view and will be released with the next version.

**Comment by ildar** [comment]
wow! ☺ 👍

**Comment by gnome17** [comment]
So finally the version is released :-) 
It is already available on Google Play and will be available on F-Droid in the next few days we think.

**Comment by ildar** [comment]
Frederik, thank you for the feature. Though that was not exactly the
feature I wanted. Though this one is useful too :)
What I wanted is the view of Albums that contain Tracks that were recently
Played.
Though recently added albums are also good :)
Could you reopen the Feature Request? Thanks!

**Comment by gnome17** [comment]
Hi,
I am glad to hear that you like the new feature even it was not the one you asked for :-)

I will create a new issue for this 'new' request. In the future it might be a good idea to add more details to your feature requests ;-)

**Comment by ildar** [comment]
Yep, my mistake, sorry.

**Comment by ildar** [comment]
Wow, accidentally both recently added and recently played features appear
in Vinyl player by AdrienPoupa . Just for the record.
