### ISSUE TITLE
Player stops randomly when using Bluetooth

### ISSUE THREAD

**Issue by avuton** [gateship-one/odyssey#171]
Hello,

Let me say first, I'm here to help, but I'm afraid I won't be able to give a detailed enough bug to be useful, I'll do all I can and answer anything that is asked.

Platform: LineageOS  Dumpling (Android 9)
Version: Latest in F-Droid
Description: When playing via Bluetooth, depending on the player, playback ceases for unknown reason.

Situation one: One car I've been in, playback stops with _every new song_ and pressing 'play' through the car will not continue playback. Only pressing play in the app continues the music, and for one song only.

Situation two: Another car I've been in, playback works perfectly. When I get out of the car and come back some time later, playback continues for about 10 second, then pauses and can't be brought back without going into the app.

I thought this was a platform issue until I used 'Phonograph', also on F-Droid, which performs the way it seems like it should. It's still a possibility that it's a platform issue, as Phonograph supports gapless playback which I suppose could be part of the issue.

**Comment by gnome17** [comment]
Hi,

thanks for sharing your issue. Unfortunately I have currently no clue what cause this issue. It sounds like a platform issue because it sounds like that you have connection issues which cause your problems.

So for the moment I have no idea how to debug this nor a bluetooth setup that I can test with.

**Comment by avuton** [comment]
I'll close for now and reopen if I get time to sprinkle in some debug info.
