### ISSUE TITLE
Is there any natural way to just play files in a folder in the order of filenames? 

### ISSUE THREAD

**Issue by ainoneko** [gateship-one/odyssey#172]
Is there any natural way to just play files in a folder in the order of filenames? 
When I open a folder, the order is random, and I don't see any way to change it. 
(The "menu button" (both the on-screen three-vertical-dots-button and the phone's "hardware menu button" ) only suggests "Reset artwork" (whatever it means),
the button depicting "+" on a sheet over another sheet (What should it mean?) says "Please wait", then nothing changes.)

**Comment by gnome17** [comment]
Hi,
I think you missunderstood the purpose of the first screen in Odyssey for a filebrowser. This is not the case. The first screen that will show up by default when you start Odyssey will show your all your music grouped by albums find in the android mediastore. The tracks from each album are sorted by their tracknumber from the mediastore.

Regarding your UI questsions: 
The "+" will add the album to your current playlist. Without starting the playback.
The "Reset artwork" option will try to load an image for your album if possible.

And finally a solution for your issue ;-) 
Just use the build in filebrowser in Odyssey. You can find it in our Navigation Side Menu under "Files". This view will show you the content of your folders sorted by filename.

I hope this helps.

**Comment by ainoneko** [comment]
Hi, 
Thank you for the explanation. It really works! ^_^
