### ISSUE TITLE
Font  stays in white when disabling Dark theme

### ISSUE THREAD

**Issue by elyaB** [gateship-one/odyssey#173]
To reproduce the bug : 
- Disable Dark theme
- Select theme to open the options
- Font is white (on white)
- Every font stays in white in every options (Sort albums by artist , Default display ...)

**Comment by gnome17** [comment]
Hi,
thanks for reporting this. It seemed that this broke when we switched to AndroidX. We will try to fix this. But I fear we have to rework our styles for that. So it could take some time.

**Comment by elyaB** [comment]
Hi, I can take a look

**Comment by gnome17** [comment]
The solution was easier than I thought.
I also noticed that the sleep timer dialog for light themes was broken.

Again thanks for your bug report :-)

**Comment by elyaB** [comment]
That was quick! Well done!
