### ISSUE TITLE
Loss my audio library

### ISSUE THREAD

**Issue by 0rganite** [gateship-one/odyssey#175]
Phone: Redmi note 4 global (mido)
Android: 7.1.2 LOS 14.1-20180728 
Odyssey: 1.1.17
Language: FR

I lost my audio library. Impossible to refresh or create a new one. I try to reinstall the app, reset the default folder, and many other things but nothing, my library is empty. I can only read music from files. I have both music on external and internal storage.
May be something wrong with the media library provided by the android system but I don't know how to check.

**Comment by djselbeck** [comment]
You can try to reset your systems media library. Go to settings->apps->show system (from menu)->search for "media storage" or something similar->storage->clear data

After this a reboot will trigger the device to rescan all media files. Afterwards you should ensure to reset your ringtone, notification and alarm sound as they will be set to a random file.

**Comment by 0rganite** [comment]
Ok thank you.
I clear media storage data and repopulate with media re.scan.
