### ISSUE TITLE
Back button exits app but notification is not dismissable

### ISSUE THREAD

**Issue by licaon-kter** [gateship-one/odyssey#18]
Xperia 5.1.1, 1.0.11 from F-Droid

**Comment by djselbeck** [comment]
The GUI and the notification are two separate processes that are independent from each other (e.g one can play music while closing the control gui). You can reopen the GUI and control the playback again(or use the notification or widget). 

This is intended behavior.

**Comment by licaon-kter** [comment]
The intended behaviour is to leave a notification stuck there until the user force closes your app from Android Settings?

**Comment by djselbeck** [comment]
The notification is bounded to playback. If playback is paused it will be cancelled after a timeout of 5minutes. If it stays there was a crash somewhere else in the playbackserver. Still no issue with GUI-Service coupling

**Comment by licaon-kter** [comment]
5 minutes is too much.

If playback is paused a `X` should be shown that helps the user close it.

If the playback is stopped (eg. end of playlist) the notification should be dismissible or it should just disappear all by itself, right away.

**Comment by djselbeck** [comment]
If playback is paused the notification is dismissible.
If playback reaches the end of the list the notifications removes itself.

Also we think that 5 minutes is the perfect time as be tested this in various practical situations. And having a notification open for 5 minutes is no big deal.

**Comment by licaon-kter** [comment]
#28 might supersede this though.
