### ISSUE TITLE
[Bug] Cannot change song in notification bar

### ISSUE THREAD

**Issue by PapistPenguin** [gateship-one/odyssey#182]
Android 8.0.0
Verizon Samsung Galaxy S7 Edge (SM-G935V)
Odyssey 1.1.18
If I play a song then go to another app then swipe down to display my notifications, only the "next" button in Odyssey's notification is available, even though it correctly displays the song being played. I can pause and play. However, no matter the position of the song in the library, the "last song" or "back" button is not visible. If I press the "next" button, the song stops and the notification closes. The song does not just pause but goes to 0:00.

**Comment by gnome17** [comment]
Hi,
the button for the previous track is only visible if the notification is expanded.

> If I press the "next" button, the song stops and the notification closes. The song does not just pause but goes to 0:00.

If it is the last track in the playlist this is the intended behaviour.
