### ISSUE TITLE
[Bug] Odyssey does not play next song in library

### ISSUE THREAD

**Issue by PapistPenguin** [gateship-one/odyssey#183]
Android 8.0.0
Verizon Samsung Galaxy S7 Edge (SM-G935V)
Odyssey 1.1.18
When a song finishes, Odyssey does not then play the next song in the library. Instead, it just stops playing music.

**Comment by gnome17** [comment]
Hi,
Odyssey has no capability to play the next song from your entire library. It will play the next song in your playlist and stop if there is no further track.

I assume you just tabbed on one track in the third tab of the  _My Music_ section. This will only add the selected track to your current playlist and not everything.

**Comment by PapistPenguin** [comment]
Okay, I guess this is more properly a feature request, then.
