### ISSUE TITLE
"Add to playlist" popup never shows

### ISSUE THREAD

**Issue by PureTryOut** [gateship-one/odyssey#184]
Because of this it's currently impossible for me to use the playlist feature, as no new songs can be added to it from any page.

**Comment by djselbeck** [comment]
The add to playlist feature of Odyssey works like a play queue. Playlist is a synonym for the list of songs to be played not a saved playlist. At least for the context menus. There is, however, the possibility to save the current playlist as a saved playlist.

You can see the current playlist by swiping up the bottom bar and clicking on the list icon at the the right top. Afterwards you can save the list from the menu.

I hope this clears things up for you

**Comment by oliverfei** [comment]
Hi, just want to mention that from a UX perspective I'd still consider this to be a minor annoyance/bug.

As a user, I am used to music/media apps referring to a "playlist" being what you refer to as a "saved playlist". The "playlist" in "Add to playlist" in the app is normally referred to as something else (e.g. "now playing", or "queue") to differentiate between a simple list and the currently playing list. So I'd suggest changing the wording to use different terms for saved playlists and the currently playing playlist.

On a more feature request note: a user should be able to create a "saved playlist" without having to add their songs to "now playing". "Add to playlist" should prompt the user to either create a new (saved) playlist or select an existing (saved) playlist to add the song(s) to.
