### ISSUE TITLE
crash with .ogg files

### ISSUE THREAD

**Issue by k2arim99** [gateship-one/odyssey#187]
# Bug Report
the app crashes when i open a .ogg file or .mkv file, it plays just fine tho

### Version of Odyssey
1.1.18

### Android Version
Oreo
### Device Manufacturer and model
Samsung J7 NEO

### Description
to bypass the issue that the android media scanner has i was changing all the extensions from .opus to .ogg and when i open those files it crashes instantly, i can tho pull over the notifications with no issues and control it from the notification ,  tho trying to even pause causes it to crash instantly
### Reproducible
i was able to reproduce it consistently even with sample .ogg files from wikimedia commons

### Expected Behaviour
to read the file
### Actual Behaviour
crashes instantlu

**Comment by djselbeck** [comment]
I can not reproduce this issue on my device with an .ogg vorbis file. 

Please send us an logcat output, otherwise there is nothing we can do

**Comment by k2arim99** [comment]
hello, sorry i think i made the title a bit misleading, they arent really ogg vorbis files but opus files with the extension changed to .ogg so android reads the metadata, it works perfectly in other players and i have found its file specific. i would like to probably a log but i dont know how to do it effectively, i do have a logcat app installed

**Comment by k2arim99** [comment]
maybe this is right? https://pastebin.com/bDKC5K6d recorded when while the crash happened opening a file from the file explorer

**Comment by gnome17** [comment]
I looked into the look you provided but there was no trace of our application in it. 

I am not familiar with the app you mentioned but if you have adb installed on your computer you could try a logcat dump via 
``` adb logcat -d > logcat.txt ```
right after the crash happens.

**Comment by djselbeck** [comment]
My music library is encoded as .ogg and works fine for a long time. I suspect there is a device issue.

**Comment by ildar** [comment]
@djselbeck , you mean OGG/Vorbis or OGG/Opus ?
https://github.com/gateship-one/odyssey/issues/187#issuecomment-538612127

**Comment by djselbeck** [comment]
Ups I overread that it was opus. Still I suspect a device issue.

I am not using opus because I do not want my music resampled up to 48khz

**Comment by gnome17** [comment]
I just tested one song with OGG/Opus and it worked without any problem.

**Comment by gnome17** [comment]
Hi,
I just tested it with the local image option and it still works normally.
The log that you provided didn't contain any crash from our application.

**Comment by ZoomRmc** [comment]
My Android 5 device can play opus-encoded files in WebM container (e.g. files, downloaded from YT with NewPipe), but not in Ogg container, giving `Odyssey:PBS:IOError`, both cases the extension is .opus.
