### ISSUE TITLE
New albums not correctly grouped

### ISSUE THREAD

**Issue by hsanjuan** [gateship-one/odyssey#188]
# Bug Report

## Setup Description

Android 10

### Version of Odyssey

1.1.18

### Android Version

10

### Device Manufacturer and model

Google Pixel 2

### Description

I have added two new albums to my Music folder by artists that were already there. This has resulted on the Artist for those albums appearing twice (rather than the new albums being grouped under their respective existing artists). One of the artists lists all the albums and the other only lists the new one.

One of the albums also has trouble sorting the tracks (seems to sort by filename). The ID3 tags of the MP3 are all correct (in terms of track numbers and artists names) and other music libraries do sort them correctly.

The music was downloaded from Amazon. Some of the song tags in both cases may encode encode special Spanish characters (ñ, á etc...), but this is not the case for the artist names and it worked well other albums before. Example tags in two different songs: one is in an album which is correctly grouped with a few other albums, and the other is however grouped as a separate artist:

Song 1: Grouped correctly in an album with is grouped with a bunch of other albums by the same artist:

```
id3v1 tag info for ¡Viva!/B074XCBVH8_(disc_1)_01_-_¡Viva!.mp3:
Title  : �Viva!                          Artist: Los Punsetes                  
Album  : �Viva!                          Year: 2017, Genre: Unknown (255)
Comment: Amazon.com Song ID: 28691512    Track: 1
id3v2 tag info for ¡Viva!/B074XCBVH8_(disc_1)_01_-_¡Viva!.mp3:
PRIV (Private frame):  (unimplemented)
TIT2 (Title/songname/content description): !Viva!
TPE1 (Lead performer(s)/Soloist(s)): Los Punsetes
TALB (Album/Movie/Show title): !Viva!
TCON (Content type): Alternative Rock (255)
TCOM (Composer): A.Paniagua
TPE3 (Conductor/performer refinement): 
TRCK (Track number/Position in set): 1/11
TYER (Year): 2017
TPE2 (Band/orchestra/accompaniment): Los Punsetes
COMM (Comments): ()[eng]: Amazon.com Song ID: 286915120
TCOP (Copyright message): Mushroom Pillow
TPOS (Part of a set): 1/1
APIC (Attached picture): ()[, 3]: image/jpeg, 36423 bytes
```

Song 2: Grouped in an album belonging to a separate artist with the same name but with a single album:

```
id3v1 tag info for Aniquilación/01 - Seres Humanos.mp3:
Title  : Seres Humanos                   Artist: Los Punsetes                  
Album  : Aniquilaci�n                    Year: 2019, Genre: Unknown (255)
Comment: Amazon.com Song ID: 20000032    Track: 1
id3v2 tag info for Aniquilación/01 - Seres Humanos.mp3:
TIT2 (Title/songname/content description): Seres Humanos
TPE1 (Lead performer(s)/Soloist(s)): Los Punsetes
TALB (Album/Movie/Show title): Aniquilacisn
TCON (Content type): Alternative Rock (255)
TCOM (Composer): Manuel Sanchez Muqoz
TPE3 (Conductor/performer refinement): 
TRCK (Track number/Position in set): 1/12
TYER (Year): 2019
TPE2 (Band/orchestra/accompaniment): Los Punsetes
COMM (Comments): ()[eng]: Amazon.com Song ID: 200000323369370
TCOP (Copyright message): Mushroom Pillow
TPOS (Part of a set): 1/1
APIC (Attached picture): ()[, 3]: image/jpeg, 35907 bytes
PRIV (Private frame):  (unimplemented)
```

In the case of the other artist/album with this problem, there are no special characters in the Artist or Album name. Normally the grouping worked well even though many songs/albums mix id3v2/v3 even v1 tags.

### Expected Behaviour

Group albums by same artists under the same artists.

### Actual Behaviour

Artist appears duplicated in the library.

**Comment by gnome17** [comment]
Hi,

thanks for your report.

Unfortunately there is currently nothing we can do about that. Odyssey is grouping by the information from the android media database and it seems that the media framework has problems with some special characters, especially in the song title. The problem could lead to split albums even if the artist or album name doesn't contain such a special character.

You could find some examples in https://github.com/gateship-one/odyssey/issues/165.

I faced the problem myself and my solution was to remove the special characters from the songs.

**Comment by djselbeck** [comment]
Duplicate
