### ISSUE TITLE
Album view no track time (all at 0:00)

### ISSUE THREAD

**Issue by licaon-kter** [gateship-one/odyssey#19]
Xperia 5.1.1, 1.0.11 from F-Droid

Tested with FLAC files

**Comment by djselbeck** [comment]
This looks like a device specific issue. Cannot be reproduced. Also odyssey just uses the system database (nothing we can influence)

**Comment by licaon-kter** [comment]
Looks like Vanilla does not get those either, Android limitation for FLACs?.

I'll retest with MP3s just in case.

**Comment by licaon-kter** [comment]
MP3s look ok, I get track time.

Regarding Vanilla, looks like I misread they info on screen, it does not show track time anyway.

**Comment by gnome17** [comment]
Tested with flac files on emulator (5.0 and 5.1) and Xperia Z (5.1.1 stock). No such issue.

**Comment by licaon-kter** [comment]
Umm, do open this back please, it does not magically get fixed on my device if it works on a different one for you.

**Comment by licaon-kter** [comment]
Back at this, no Xposed installed even.

Now, having mp3 and flacs in the same folder makes this broken for all now. :(
