### ISSUE TITLE
Save playlist creates an empty file

### ISSUE THREAD

**Issue by bunyevacz** [gateship-one/odyssey#194]
Queue of the audio files->[...]->Save playlist->Create New playlist->somename

It creates an empty file named "somename" under /storage/emulated/0/Playlists/somename

I tested it on version 1.1.18 (from f-droid), under Android 8.1.0 (Nokia 8.0), and also under Android 9

Any idea how to debug it further?

**Comment by djselbeck** [comment]
Odyssey does NOT create playlist files. Playlists are stored only inside Android's internal media database. 

However, we are investigating how to get rid of the dependency of Android's media database at the moment. Exporting playlists to files is a high priority item on my list

**Comment by ildar** [comment]
>
> , we are investigating how to get rid of the dependency of Android's media
> database at the moment.
>
Guess the Vanilla player devs already explored it all. They seem to use
both media db and their own.

**Comment by gnome17** [comment]
With the latest version of odyssey (1.1.20) we changed the playlist logic and we will now save playlists internally.

The mentioned issue should be solved with this change.

A file export functionality might be added in the future.
