### ISSUE TITLE
Search feature: keep query when switching between categories

### ISSUE THREAD

**Issue by dennisguse** [gateship-one/odyssey#199]
# Feature request

I was just using search to look for an artist (search query entered).
However, I was actually in the album pane.
So, I switched to the artists pane - but my search query disappeared and I needed to enter it again.

Expected behavior:
When switching the from search pane to another: apply an already entered search query.

**Comment by gnome17** [comment]
It was designed this way by intention but meanwhile I found it counterintuitive myself.

We will keep your input in mind and I think we will change the behaviour in the future.

Thanks for your input.

**Comment by gnome17** [comment]
Hi,

It took way longer than we would expected but it is implemented in the master branch of odyssey.

We are still in our android 10 test phase after we were able to resolve all open issues we will release a new version of odyssey.

Until then I will leave this issue open as a reminder to release a new version asap ;-)

**Comment by gnome17** [comment]
Finally released ;-)

Should be available on Google Play today and in a couple of days on FDroid as well.
