### ISSUE TITLE
Album view no track play on click

### ISSUE THREAD

**Issue by licaon-kter** [gateship-one/odyssey#20]
...but play if added to playlist

Xperia 5.1.1, 1.0.11 from F-Droid

Tested with FLAC files

**Comment by djselbeck** [comment]
We'll investigate this one.

**Comment by licaon-kter** [comment]
OK, I'll back out, it won't even add tracks on `add to playlist` now.

**Comment by djselbeck** [comment]
We're sad to here that you have issues with the application. As we are only doing this as a hobby we can't afford a lot of test devices. Also we never used ROMs using the Xposed framework. 

Here is a list of tested devices:
- Amazon Fire Tablet Ford (CM12.1)
- Oneplus Two (Stock FW)
- Xperia Z (CyanogendMod/Stock FW)
- Xperia Z3C (Stock FW)
- Xperia XZ (Stock FW)
- BQ M5 (CM 13.0)
...

We tested ogg,mp3, wav and flac playback on all off these devices without problem. We are not sure whats wrong with your system but to be honest I think it is a bit out of scope for us.

**Comment by licaon-kter** [comment]
It's a stock Z3, BTW.

**Comment by licaon-kter** [comment]
MP3s work ok, they get added fine from Album view, they play fine directly from Album view.

**Comment by gnome17** [comment]
Tested with flac files on emulator (5.0 and 5.1) and Xperia Z (5.1.1 stock). No such issue.

**Comment by licaon-kter** [comment]
Umm, do open this back please, it does not magically get fixed on my device if it works on a different one for you.
