### ISSUE TITLE
[Bug] No Subdirectory Search

### ISSUE THREAD

**Issue by zero77** [gateship-one/odyssey#204]
# Bug Report

## Setup Description
Play store

### Version of Odyssey
1.1.19
### Android Version
9
### Device Manufacturer and model
Samsung
### Description
Unless i have been doing something wrong, i am only able to search for content in the current directory and not in any of the subdirectories.

**Comment by gnome17** [comment]
Hi,
you don't missed something. We only support search operations in the current directory.

To search in a sub directory you have to access this sub directory first.

So this is technically a feature request and not a bug because the search functionality works as intended.

**Comment by zero77** [comment]
Should i reopen this as a feature request.

**Comment by gnome17** [comment]
yes please :)

**Comment by zero77** [comment]
As requested, i have reopened this:
https://github.com/gateship-one/odyssey/issues/205
