### ISSUE TITLE
All tracks view no track time (all at 0:00)

### ISSUE THREAD

**Issue by licaon-kter** [gateship-one/odyssey#21]
Xperia 5.1.1, 1.0.11 from F-Droid

Tested with FLAC files

**Comment by djselbeck** [comment]
This looks like a device specific issue. Cannot be reproduced. Also odyssey just uses the system database (nothing we can influence)

**Comment by licaon-kter** [comment]
MP3s look ok, they get track time.

**Comment by gnome17** [comment]
Tested with flac files on emulator (5.0 and 5.1) and Xperia Z (5.1.1 stock). No such issue.

**Comment by licaon-kter** [comment]
Umm, do open this back please, it does not magically get fixed on my device if it works on a different one for you.

**Comment by djselbeck** [comment]
This issue is not with this software but with the android system. Is your system rom clean? No xposed? no other modifications? It makes absolutely no sense, that the application is working so crazy on your device. Which tool did you use to encode flacs?
