### ISSUE TITLE
Naming of playlist skipped on creation

### ISSUE THREAD

**Issue by L3br4nd** [gateship-one/odyssey#213]
When trying to create a new playlist, the step at which the playlist can be named is skipped, which leads to a new playlist named "create new playlist". I could not find an option to rename the playlist after creation, therefore I am stuck with the playlists I had created before and can only change the "create new playlist" playlist. This behavior was first seen in Version 1.1.20

![Screenshot_20201221-072129_Odyssey](https://user-images.githubusercontent.com/17169028/102745864-48f57f00-435d-11eb-8f95-44b53f435395.png)
![Screenshot_20201221-072635_Odyssey](https://user-images.githubusercontent.com/17169028/102746136-ec469400-435d-11eb-92ee-3b154873926c.png)

Phone: Fairphone 2
OS: /e/OS 0.13 2020120889008-dev-FP2
![Screenshot_20201221-071743_Einstellungen](https://user-images.githubusercontent.com/17169028/102745872-4d219c80-435d-11eb-9ef1-e44afc8913f2.png)

**Comment by gnome17** [comment]
Hi,

renaming of playlists is currently not implemented but should be easy to add this.

I wasn't able to reproduce your issue could you please explain in more detail what you mean with "skipping the name step"?

**Comment by L3br4nd** [comment]
Hi, 
sure. In the meantime I uninstalled Version 1.1.20 and reinstalled 1.1.19. I got an error message when I tried to downgrade directly...
When I press the button "Neue Playlist erstellen" (create new playlist), the window which can normally be used to set the name, or select a playlist to overwrite, pops up for a millisecond and then the list of playlists appears with the new playlist named "Neue Playlist erstellen".

I hope this is helpful. Is it possible to create logs, or should I try to create a video?

**Comment by gnome17** [comment]
Hi,

please keep in mind that we don't support a downgrade of odyssey. It may work most of the time but in any case its safer to do a clean install.

I assume playlist creation was working prior to 1.1.20?

I doubt that a video will help us to understand the issue but we would really appreciate logs if you could manage to create them.

If you have adb installed on your computer you could try a logcat dump via
```adb logcat -d > logcat.txt```
right after the you created a playlist and the issue occurs.

I know there are some android apps around that could do the same thing but I am not familiar with those and cannot recommend any.

**Comment by gnome17** [comment]
So I finally encountered the bug myself.

The issue was a combination of incorrect sorting and not setting all attributes properly.

I already pushed a fixed will do brief tests, after that we will release a new version.

**Comment by gnome17** [comment]
New release is done. Should be available in the Play Store today and on F-Droid in the next days.

I will close the issue now. If this release doesn't fix the problem you encountered feel free to reopen the issue again.

And sorry it so long to fix it ;)

**Comment by L3br4nd** [comment]
Thank you very much :-)
I figured this would be hard to reproduce and analyse, so I'm glad you were able to find the issue and a solution.
