### ISSUE TITLE
Add a hint to NowPlayingView for new users

### ISSUE THREAD

**Issue by licaon-kter** [gateship-one/odyssey#22]
...yes, you can slide up but that's not intuitive, I found it by mistake

Xperia 5.1.1, 1.0.11 from F-Droid

Tested with FLAC files

**Comment by djselbeck** [comment]
We thought about this some time. We also investigated how other applications are doing it. There is a  number of application that do the same thing (e.g soundcloud, google play music, ...).

We do think that it is intuitively. But we also thought about adding a hint for first starts.

**Comment by gnome17** [comment]
We add a hint with version 1.1.2.

The NowPlayingView will slide up on first play.
