### ISSUE TITLE
When going back to Album library from an album tracklist, be sent back to where I was

### ISSUE THREAD

**Issue by BesseOnline** [gateship-one/odyssey#232]
# Feature request

When going back to Album library from an album tracklist, it would be good to be sent back to where we were scrolling, and not at the beginning of the library. Example : I scroll my album library looking for something to listen, then taps on the 'Renegades' album by RATM. But I change my mind and want to go back scrolling for something else. When I go back in my album library, I am sent back to the start, but I would prefer being sent back to where I was before, somewhere in the letter 'R'.

Thanks!

**Comment by SpringerJack** [comment]
Had a look around, it seems like this bug was introduced with _005835269af99eae73b0a13cacce386334c20ee0_.

**Comment by gnome17** [comment]
Hi,
thanks for your effort. I can confirm that it seems that this commit was the issue. I am not sure why though yet, but I will investigate it further when I have time.
