### ISSUE TITLE
ability to shuffle all songs

### ISSUE THREAD

**Issue by u6aab** [gateship-one/odyssey#234]
# Feature request

first of all, thanks for developing this, its a great player. the only thing id like to see would be a way to shuffle all songs. right now i have a playlist with all my songs, but i sometimes forget to add new songs to it. either some way to shuffle all songs from the songs tab or an "all songs" playlist that automatically added any new songs on startup would be nice.

**Comment by foldfree** [comment]
The way I shuffle all song in Odyssey is:

1.  I start playing a song in the 'all tracks' tab. 
2.  I turn on the shuffle option. 

It's not a one click solution as most music apps seems to have but it works.

**Comment by gnome17** [comment]
Hi,
as stated by @foldfree this is currently the only option to shuffle all songs.

**Comment by u6aab** [comment]
when i open a song from the all tracks tab and turn shuffle on it, it just repeats at the end of the song.

**Comment by foldfree** [comment]
> when i open a song from the all tracks tab and turn shuffle on it, it just repeats at the end of the song.

My bad, you must use the floating button, not any songs. all the tracks should show up in the queue when done like that.

**Comment by u6aab** [comment]
thanks, it works now
