### ISSUE TITLE
.nomedia not respected in Files view

### ISSUE THREAD

**Issue by licaon-kter** [gateship-one/odyssey#24]
Xperia 5.1.1, 1.0.11 from F-Droid

Tested with FLAC files

**Comment by djselbeck** [comment]
In what respect should it be respected? When adding recursively? Showing files?

**Comment by licaon-kter** [comment]
Always.

If that folder has a `.nomedia` inside, just skip it and its subfolders.

**Comment by gnome17** [comment]
Fixed with commit 2533599
