### ISSUE TITLE
My Music tabs stuck on top

### ISSUE THREAD

**Issue by licaon-kter** [gateship-one/odyssey#26]
Steps:
* My Music
* have no artist detected, but album and plenty of tracks
* go to all tracks and scroll down so the artist/album/alltracks icons are scrolled up top
* switch to artist (where you have no artist there)
* you can't scroll down the view to get the `My Music`text visible

Xperia 5.1.1, 1.0.11 from F-Droid

Tested with FLAC files

**Comment by gnome17** [comment]
This bug should be fixed with commit  fe2048b
