### ISSUE TITLE
"Legasy theme" is broken

### ISSUE THREAD

**Issue by AntyElo** [gateship-one/odyssey#265]
### "Legasy theme" option crash application
Version of Odyssey: >=1.3.0
Android Version: 13
Device Manufacturer and model: Samsung SM-A145F

### How reproduse
Set theme to "Light Green"
Switch "Legasy theme"

**Comment by gnome17** [comment]
Hi,

thanks for reporting this. It seems we missed this during the introduction of the new themes.

We try to fix this as soon as possible.

**Comment by gnome17** [comment]
Hi,

the new release is done (https://github.com/gateship-one/odyssey/releases/tag/release-41). All themes should work again now. 

Thanks again for reporting it :)

Depending from where you installed odyssey it might take some time until the update is available.

**Comment by AntyElo** [comment]
thanks, it work
