### ISSUE TITLE
My Music is an empty view

### ISSUE THREAD

**Issue by licaon-kter** [gateship-one/odyssey#27]
Steps:
* open a track
* go to Now playing
* hit home button (go to launcher)
* touch notification
* Now playing opens up
* hit back button
* My Music view is empty, no tabs for artist/album/alltracks
* open menu->My Music fixes it

Xperia 5.1.1, 1.0.11 from F-Droid

Tested with FLAC files

**Comment by djselbeck** [comment]
We also encountered this issue after upgrading to new support library and this likely the same and will be fixed with 1.1 release.

**Comment by gnome17** [comment]
Fixed in release 1.1.0

https://github.com/gateship-one/odyssey/releases/tag/release-12
