### ISSUE TITLE
App crash on my music tab switching

### ISSUE THREAD

**Issue by licaon-kter** [gateship-one/odyssey#29]
Xperia 5.1.1, 1.0.11 from F-Droid

Tested with FLAC files

Had this a lot for a while, but after a clean data, I can't repro them:
log1: https://gist.github.com/licaon-kter/1a85c5eea71257679f7ff7f2319b62a9
log2: https://gist.github.com/licaon-kter/7412fb19b1ff03b3e77d7b0d73f37503

**Comment by gnome17** [comment]
Thanks for the log files. This issue will be fixed with Version 1.1.

**Comment by gnome17** [comment]
Fixed in release 1.1.0

https://github.com/gateship-one/odyssey/releases/tag/release-12
