### ISSUE TITLE
Null pointer crash in GenericViewAdapter

### ISSUE THREAD

**Issue by licaon-kter** [gateship-one/odyssey#3]
F-Droid build on Xperia 5.1.1 (root+Xposed) and Samsung 5.0.2 (no root)

The devices have SD card support, that would be mounted on `/sdcard1/` if present, but they don't currently have such a card inserted.
This error was seen in other apps too, but should not be fatal.

logcat: https://gist.github.com/licaon-kter/ee332402ce5d8cbd9bf3bf0faa33b804

**Comment by djselbeck** [comment]
Thank you for the report and your time. We will fix this issue as soon as possible. We might get back to you to investigate the issue of these two devices.

**Comment by djselbeck** [comment]
We fixed the issue with release version 7. It will be uploaded to google play now. We check how to push it to f-droid as we are no maintainer there. 

Thanks again for reporting this bug with a detailed logcat.

**Comment by djselbeck** [comment]
Until the release comes to F-Droid you can use this APK: https://owncloud.djselbeck.de/index.php/s/zztdkkKgm5DKbys . It is signed by our google key so you have to uninstall the apk from f-droid first. Sorry, we don't have the signing information from f-droid ;)

**Comment by licaon-kter** [comment]
Your build, at least now shows the app interface for a second, but then it crashes again: https://gist.github.com/licaon-kter/b978a3a2ffe7205a76165d878c86dc4e

**Comment by djselbeck** [comment]
Thanks we'll investigate this. Very strange crash thanks again for the helpful log.

**Comment by licaon-kter** [comment]
I should have opened another issue I guess.

Anyway, an update, this happens only on Xperia 5.1.1 (root+Xposed), and not on Samsung 5.0.2.

**Comment by gnome17** [comment]
We have prepared a new test build that should fix this crash. We would appreciate feedback about this build. Thanks again for your helpful debugging. You can find the link to the build below:

https://owncloud.djselbeck.de/index.php/s/vv1uL4mWU1csPmH

**Comment by licaon-kter** [comment]
This fixes it. Thanks
