### ISSUE TITLE
Feature Request: Add a Podcast section

### ISSUE THREAD

**Issue by klundry** [gateship-one/odyssey#30]
Along with the Music, Playlists, Bookmarks and Files functions, it would be nice to have one specifically for podcasts.  

I'm thinking you could set the folder to look for podcasts and also hide them from the rest of the sections.  Currently, when I go to Music my podcasts are mixed in with the actual music even though they are in a different folder.  It's not ideal to have podcasts start when you are trying to listen to your music.

If it could also hide or gray out podcasts that have been listened to that would be great.

**Comment by gnome17** [comment]
Thanks for your feedback. 

We are retrieving the music files from the android media database. So maybe we can filter podcasts but there is no guarantee that this will work properly but we will test it in the future. 

We are currently not planning to add a feature to mark tracks as listened.

**Comment by gnome17** [comment]
In the next release (1.1.4) we will filter all tracks that are marked as podcast in the mediastore. This can be achieved if they are located in a folder called "Podcasts". This folder should be located in the root directory of your storage volume.

In our opinion this will resolve this issue.

**Comment by klundry** [comment]
Can you clarify what you mean by root of storage volume? Is that my root music folder that I have configured? Or the root of my internal storage?

Currently, I have a folder that I sync to my phone with syncthing that has my podcast folder inside of it.  So, "internal storage root">sync folder>podcasts

**Comment by djselbeck** [comment]
Android has certain system default folders. Like Alarms, Ringtones, ... and one called Podcasts. 
The system use these directories to identify ringtones or alarm tones or podcasts. 

This means that the Media library of Android detects podcasts if they are in the Podcasts folder inside the internal sd (/storage/emulated/0/Podcasts for me) or the external SD card (/storage/SOME-UUID/Podcasts)

**Comment by klundry** [comment]
Ok. So I guess I'll have to rethink how I sync my podcasts to my phone, ugh.
