### ISSUE TITLE
Contextual menu disappears on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [gateship-one/odyssey#32]
When i perform these sequences of events, the menu on screen disappears:

Sequence 1-3:
1. Select:
a. album view
b. Artist view
c. Audio view
2. Long click on item in list
3. Orientation Change

Sequence 4:-6
1. Open Side Drawer
2. Click on:
a. Playlists
b. Bookmarks
c. Files
3. Long click on item in list
4. Orientation Change

**Comment by gnome17** [comment]
We investigated the issue and came to the conclusion that this behaviour is consistent with all other applications we tested. For example the offical YouTube application also has a disappearing context menu (triggered with the dot menu button).

Other open source applications like k9-mail also show the same behaviour. 

As a result we decided to not change this behaviour.

**Comment by reverse-unina** [comment]
In Youtube if I perform this sequence of events, the contextual menu does not disappear:
1. Click on Search icon
2. Enter text
3. Long click on a result item
4. Orientation Change

Other open source applications on F-Droid, e.g. Transistor also show a correct behaviour (persistence of the menu).

We know that other apps show this failure. Most of them, like Google Docs, corrected this behavior.
