### ISSUE TITLE
Dialog disappears on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [gateship-one/odyssey#33]
When i perform these sequences of events, the dialog on screen disappears:

Sequence 1:
1. Open Side Drawer
2. Click on Files
3. Click on ...
4. Click on Add Directory to playlist
5. Orientation Change

Sequence 2:
1. Open Side Drawer
2. Click on Settings
3. Click on Artwork Settings
4. Click on Try to load all images...
5. Orientation Change

**Comment by gnome17** [comment]
Fixed it. 
Commits: 
- 4873dfb
- 109c863
