### ISSUE TITLE
[enhancement] Hide Covers

### ISSUE THREAD

**Issue by Num2** [gateship-one/odyssey#38]
An option to hide covers would be nice, i have some "offensive" covers in my libary and while you're in public it could get a bit weird.

**Comment by djselbeck** [comment]
Thanks for your extraordinary feature request, we implemented this feature in a separate [branch](https://github.com/gateship-one/odyssey/tree/hide_artwork), because this is quite a big feature (in number of code modifications) and are currently testing it.

**Comment by gnome17** [comment]
Testing is done and feature will be released with version 1.1.2.
