### ISSUE TITLE
[feature request] Allow to share music files

### ISSUE THREAD

**Issue by gsantner** [gateship-one/odyssey#39]
When selecting a single track please allow to share the music file to other apps.
If possible, also allow it from the toolbar overflow-menu while playing a song, and showing the playback view.
Sometimes I playback some track I would like to listen on my media center, or want to send somebody. Would be really great if this player could also allow me to do this.
Note: May be about 3 lines of code (`new Intent()..`), and the xml entries.

**Comment by gnome17** [comment]
We added the option to share the current song from the playback view. After tests are done we will consider to integrate this option in other screens.

**Comment by gsantner** [comment]
@gnome17 
Tested sharing current song. Works as intended, would appreciate integrations in other views.
