### ISSUE TITLE
Be able to open supported files from a file browser

### ISSUE THREAD

**Issue by LoneFenris** [gateship-one/odyssey#41]
Odyssey currently doesn't register as able to play its supported filetypes and so can't be selected to open files from a file browser.

**Comment by djselbeck** [comment]
Thanks for the request.

We will check this out in the future, for now Odyssey also has an inbuilt filebrowser where you can browse your media files from different volumes (selectable from the menu in the right corner)

**Comment by gnome17** [comment]
This feature is implemented in version 1.1.7. It is already available at Google Play and will be available on F-Droid in the next few days we think.
