### ISSUE TITLE
[FR] Scrobbling tracks to libre.fm/last.fm

### ISSUE THREAD

**Issue by pank** [gateship-one/odyssey#43]
Hi,

Thanks for working on Odyssey.  It works great.

It would be nice if tracks could be scrobbled to libre.fm and last.fm.  Perhaps it is better to do it via an external program like [simple last.fm scrobbler](https://github.com/tgwizard/sls).

Thanks,
Rasmus

**Comment by djselbeck** [comment]
Hi, 

SLS is currently already supported.

**Comment by pank** [comment]
Hendrik Borghorst <notifications@github.com> writes:

> SLS is currently already supported.

It is.  Sorry about the noise and thanks!

**Comment by djselbeck** [comment]
No problem, you're very welcome and we missed to write it in the README
