### ISSUE TITLE
App crashes immediately upon opening

### ISSUE THREAD

**Issue by angus-parvis** [gateship-one/odyssey#5]
The app crashes immediately after opening. It shows blue screen with Odyssey logo for half a second, then disappears.
My phone is Redmi Note 3 Pro (Qualcomm). Android version: 5.1.1 LMY47V. MIUI version: MIUI Global 8.0 | Stable 8.0.5.0(LHOMIDG).

**Comment by djselbeck** [comment]
Thanks for reporting the issue.

Can you please tell us, which version you are using? Is it from google play or f-droid? If it is from google can you send the bug report? If it is from f-droid can you try the apk from here: https://owncloud.djselbeck.de/index.php/s/zztdkkKgm5DKbys . It may be related to issue #3

**Comment by angus-parvis** [comment]
I used version from F-Droid. This apk fixed my problem. I think it is the same issue, because my device doesn't currently have SD card insterted. Thanks.

**Comment by djselbeck** [comment]
Thanks for your quick response ;) so we are closing this.
