### ISSUE TITLE
Be more helpful if Equalizer app isn't installed

### ISSUE THREAD

**Issue by dalb8** [gateship-one/odyssey#52]
At the moment it just says there isn't any Equalizer app installed. It could suggest where to find one that is free software. I don't know of any myself apart from DSP Manager or the one in Lineage OS but they can't be installed as regular apps.

**Comment by gnome17** [comment]
Hi,
we don't know any equalizer app and we think the message is just fine as it is.

If you know any app we will consider changing the message.
