### ISSUE TITLE
.opus files take a really long time to start playing

### ISSUE THREAD

**Issue by Trevonn** [gateship-one/odyssey#53]

**Comment by gnome17** [comment]
Hi, .opus files are not recognized from the android media service as music files. So we have to read the tag of the files manually to get the track information. This can be time consuming.

**Comment by gnome17** [comment]
Hi,
we discussed the problem and we think we could improve the playback start time, so that you are able to start listening to the music even if the app doesn't have all track informations already.

**Comment by bb010g** [comment]
Any progress on this?

**Comment by gnome17** [comment]
Hi,
we didn't forget this issue but we have currently not much time to spent on odyssey. It won't be fixed with the next release but after that we will investigate this further and try some ideas we have to improve the playback start time.

**Comment by gnome17** [comment]
Hi,
we finally released a new version (1.1.7) that should improve the playback start. It is already available at Google Play and will be available on F-Droid in the next few days we think.
