### ISSUE TITLE
No previous option in lock screen controls

### ISSUE THREAD

**Issue by kalenpw** [gateship-one/odyssey#54]
On the lock screen notification/controller there is not an option for previous. 

I tried poking around in `OdysseyNotificationManger.java` to see if there were any obvious mistakes and also tried resizing the icons in case previous was getting cut out, but still can't see previous. 

[image](http://i.imgur.com/l2p4uzz.png)

**Comment by gnome17** [comment]
Hi, 
we wanted to achieve as much space as possible for the trackinformation. But you have the previous option if you expand the notification just like you can expand other notifications.

**Comment by kalenpw** [comment]
Ah I see, didn't even think of expanding the notification. I ended up changing it to `notificationStyle.setShowActionsInCompactView(0, 1, 2);` as I find myself wanting to go back often enough it is convenient to have there. Thanks for the explanation.
