### ISSUE TITLE
Shuffle just picks random tracks?

### ISSUE THREAD

**Issue by JamesHealdUK** [gateship-one/odyssey#65]
Love this player, it's awesome!

Only thing is, the shuffle button works but it will play tracks twice in the same session. So if i play all and press shuffle, 2 tracks later i might come across the first track again etc.

**Comment by gnome17** [comment]
Hi,
we are glad to hear that you like odyssey.

You are right we don't keep track of already played tracks. For your purpose I suggest that you use the already implemented shuffle feature. You can activate shuffle via the options menu in the same view.

**Comment by JamesHealdUK** [comment]
Hi!

Definitely, keep up the good work, this is a seriously killer app. Ive not come across another music application as snappy as this, yet alone a FOSS one!

In response to the shuffle thing, I got it working by pressing play on all tracks, then sliding up the currently playing track, pressing the playlist button at the top right and then pressing the 3 dotted menu to get to the "shuffle playlist" as it seems the shuffle button in the bottom right corner just randomises which tracks play.

Heres some pictures guiding the process for those wondering: http://imgur.com/a/4Ltvy

And thanks again for such a fantastic player. Its apps like this that make it possible for people to make the switch to a more open experience.

**Comment by Klev42** [comment]
Hello, newbie user of github here. I personally think that it will be a great idea to change what does the shuffle button. The current behaviour is frustrating for me so I suppose it can be the same for new users who likes to shuffle.
If my post is inappropriate don't hesitate to delete or move it. Have a good day and thank you for your very good job on Odissey!
