### ISSUE TITLE
[FR] External audio output only

### ISSUE THREAD

**Issue by pzrjcjgd** [gateship-one/odyssey#68]
Is it possible to implement feature as follows — checkmark that enables only external audio output (like headphones) and when it is disconnected current song is paused. It would by very handy.

**Comment by gnome17** [comment]
Hi, 
since this feature is already implented and working we are not quite sure if we understand your feature request. Odyssey will pause the current song if your headphones are disconnected.

**Comment by pzrjcjgd** [comment]
Yes it's there, but a option to tick on/off would be nice.

**Comment by gnome17** [comment]
Hi,
as we stated in #40 we will not add an option for this.
