### ISSUE TITLE
Equalizer (Again)

### ISSUE THREAD

**Issue by surferjoeit** [gateship-one/odyssey#69]
Hello again,
i tested new release and  sadly noticed that on my device nothing changed. I still can't open equalizer from menu drawer.
I can open it from playback screen but it doesn't work. It seems i can just turn it on and off but audio output doesn't change.
Audio output is only modified by the equalizer when i open and use it from stock music player and the setting is then preserved when playing music with odyssey with no possibility to modify it.
Hope my description is clear enough....
Thanks
Francesco

**Comment by gnome17** [comment]
Hi,
you might no like this but currently we have no option to reproduce your issue. Currently none of our devices show the problems your mentioned. So to be honest it will be difficult to locate your problem.

What device and rom are you using?

**Comment by surferjoeit** [comment]
I have a Wiko Ridge 4G, android 5.0.2.

Thanks

Sent from my WIKO RIDGE 4G

Il 26/mag/2017 19:55 Frederik Lütkes <notifications@github.com> ha scritto:

**Comment by djselbeck** [comment]
Issue #61 should be referenced

**Comment by djselbeck** [comment]
Hello, 
i've tested some changes and on my Xperia XZ it helped. So if you would like you can test an alpha test version with some eq changes with the following APK:

[APK download](https://owncloud.djselbeck.de/index.php/s/GvuczJgYicykrPS)

**Comment by surferjoeit** [comment]
Hello, i tested it and nothing changed, sorry...

**Comment by djselbeck** [comment]
Then it looks like there is nothing we can do I guess. :) I've noticed that some applications start playing videos automatically (twitter,fb and others) that block the eq in some cases for me.

**Comment by surferjoeit** [comment]
I'm not a developer so i cannot help you, sorry. I can only add that i used to use Vanilla Music, which i abandoned for other reasons, and with that one it worked....

**Comment by djselbeck** [comment]
I really don't know why it does not work. I've checked the vanilla source code and found no significant differences in eq handling.

I've tested the EQ working on all my accessible test devices:
BQ Aquaris M5
BQ X5+
Sony Xperia XZ
Sony Xperia Z
Amazon Fire Tablet 7" (ford) with cyanogenmod.

It works on all of them so as much as I'd like to help I really don't see how anymore.

**Comment by surferjoeit** [comment]
Thanks a lot for your effort in trying to fix this issue just for me.... I can live without the equalizer, don't worry...

**Comment by djselbeck** [comment]
One last try if you don't mind, we were missing some parameters when opening the Equalizer.

Can you try this [apk](https://owncloud.djselbeck.de/index.php/s/2IpQG154vixps0u) ?

And please make sure to open the equalizer directly out of odyssey.

**Comment by surferjoeit** [comment]
Whow! Now it works! Many thanks.
Just to clarify: now it works perfectly when i open the equalizer from playback screen.
When i try to open it from the menu drawer, it opens (previously not), but it doesn't work. It works only from playback screen
Thanks again!

**Comment by k2arim99** [comment]
Hello I'm having the same problem unfortunately, it doesn't open on the main screen and only does on the playback one while doing nothing

**Comment by surferjoeit** [comment]
In my case this https://owncloud.djselbeck.de/index.php/s/2IpQG154vixps0u solved (partially) the problem.

**Comment by djselbeck** [comment]
We will release a version with these fixes soon. 

The remaining problems are mostly due to the devices android systems. On my AOSP based firmware for example MP3s are offloaded to a DSP for decoding and bypass all the android audio system. The equalizer does not work in this case. So if equalizer is still not working, we cannot do anything about it.

Why the EQ ist working from nowplaying and not from the settings is currently unclear for us, because the call to open the settings is 1:1 identically 😄

**Comment by gnome17** [comment]
We finally released the new version. It is already available at Google Play and will be available on F-Droid in the next few days we think.
