### ISSUE TITLE
[FR] .cue file support

### ISSUE THREAD

**Issue by Veterok** [gateship-one/odyssey#73]
Some albums are distributed as a single audio file with an accompanying .cue file. Ideally, these would populate a playlist, rather than appearing as a single long track.

**Comment by Veterok** [comment]
Example .mp3 .cue file combination in the .zip download here:
https://archive.org/details/elpa37

**Comment by gnome17** [comment]
Hi,
sorry for the long delay. To be honest this is out of scope at the moment. 
So if you want to use odyssey the only way at the moment is to split your files (e.g. https://wiki.archlinux.org/index.php/CUE_Splitting).
