### ISSUE TITLE
Notification with controls

### ISSUE THREAD

**Issue by licaon-kter** [gateship-one/odyssey#8]
At least Play/Pause and Next.

**Comment by djselbeck** [comment]
The notification is the standard MediaControl notification provided by the api and it has controls. Can you provide a screenshot of the notification on your device (which?)?

https://play.google.com/store/apps/details?id=org.gateshipone.odyssey you see there how the notification should like.

**Comment by licaon-kter** [comment]
My bad, the test WAV ( #7 ) did not trigger it. :)
