### ISSUE TITLE
[FR] auto bookmark

### ISSUE THREAD

**Issue by ildar** [gateship-one/odyssey#81]
When a user chooses an Album/Playlist/a Bookmark/etc. and the whole play queue is replaced, the app could save current queue into "Auto bookmark" (should be named properly)

**Comment by djselbeck** [comment]
I don't like the idea of it. If a user wants to save his current position/pl he can already create a manual bookmark. How should automatic bookmarking work? One bookmark everytime the playlist is replaced? This would be quite confusing to the user and it would also result in a lot of unnecessary created bookmarks that are annoying to be removed.

**Comment by ildar** [comment]
1. No, just one bookmark with special name, e.g. "Automatically saved
bookmark"
2. It is overwritten only when the playlist is flushed and replaced.
3. I think bookmarks should be more dynamic, see e.g.
https://github.com/gateship-one/odyssey/issues/84

**Comment by gnome17** [comment]
We don't intend to implement this feature request.
