### ISSUE TITLE
No way out of the folder view

### ISSUE THREAD

**Issue by schmolch** [gateship-one/odyssey#83]
I prefer the folder-view which I also set as the default view, but now I can not find a way to get into the settings anymore. Pressing back repeatedly just cycles between my default folder and it's parent.
Sorry if I'm missing something.

**Comment by djselbeck** [comment]
Try swiping from the left. The menu should appear

**Comment by schmolch** [comment]
Ah yes it does. Thank you.

Am 16.07.2017 01:01 schrieb "Hendrik Borghorst" <notifications@github.com>:
