### ISSUE TITLE
Bookmarks should follow playback

### ISSUE THREAD

**Issue by ildar** [gateship-one/odyssey#84]
When a user saves a bookmark or restores a bookmark, his playlist is clearly associated with this bookmark. Then I suggest the bookmark should "follow" the playback, i.e. the current position in the bookmark should automatically update.

**Comment by Pazns** [comment]
It completely breaks the purpose of a bookmark in Odyssey.

A bookmark points to a specified, fixed, time.

**Comment by ildar** [comment]
Emm, alright. I can agree on the Creator's view if it was so.
But also you: accept that Bookmark can theoretically behave as proposed,
just like a book bookmarks "follow" the reading process of a human.
Agree on an option? Deal? 😉

**Comment by Pazns** [comment]
@ildar : 
But what is the use case ?
Do you have a real example when you needed to automatically adjust your bookmark in real-time, and you couldn't just add a bookmark just the second before destroying your playlist and current track ?

**Comment by ildar** [comment]
Use case: I have a big collection of game music. And want to gradually
listen the whole. Want to track the progress.
In the meanwhile I want to listen to other albums and at times get back to
the collection.
"Dynamic" bookmarks is quite natural behavior.
IMHO both static and dynamic bookmarks are quite viable concepts.

**Comment by Pazns** [comment]
@ildar 
Your use case seems far enough for the current bookmark concept in Odyssey to ask for a whole new mechanism, don't you think ?

**Comment by ildar** [comment]
I think this up to any developer wanting to implement this feature. Can I
ask leaving this as a feature request?

**Comment by Pazns** [comment]
You can do whatever you want.
Also, I am not the repo lead, I was just passing by and saw this issue ticket.

What I was saying is, you seem to say the bookmark is incomplete right now (« _Bookmark **should** [ ]_ »).
But what you describe is not really what a simple real-life bookmark do.

_**K**eep **I**t **S**imple and **S**tupid, and avoid feature creep_.

**Comment by gnome17** [comment]
We don't intend to implement this feature request.

**Comment by nofishonfriday** [comment]
I found this issue looking for the same feature (resp. #81) in odyssey, [Musicolet](https://play.google.com/store/apps/details?id=in.krosbits.musicolet) has this, it's called multiple queues.
