### ISSUE TITLE
Reformat track numbers

### ISSUE THREAD

**Issue by zayuim** [gateship-one/odyssey#86]
I think the app should format tracks numbers differently. Instead of it being "02 -" it should be "02. ".

And even better if you can make the 0 not appear where applicable so basically " 1. " and "10. "

**Comment by djselbeck** [comment]
We don't think so. We show 01.01 for albums with multiple discs. To separate this we show e.g "01.01 - Cool track". Do you see? You can clearly distinguish between the disc & track number and the track title. With "01.01. Cool Track" it is not as clear.

**Comment by zayuim** [comment]
@djselbeck I understand what you mean but I must say my favorite method of handling this is: 
 8. Track
 9. Track
10. Track
11. Track
 1. Track
 2. Track
 3. etc.

Maybe having it as an option would be cool?

**Comment by gnome17** [comment]
We don't plan to change it.
