### ISSUE TITLE
Select music folder(s)

### ISSUE THREAD

**Issue by github-user-1** [gateship-one/odyssey#87]
Maybe I overlooked it, but I can't find an option to select my music folders (only one option to go back to the root folder, but nothing is happening there).

Background - I have lot's of audio books, recordings, podcasts, music, etc. which currently all show up in odyssey. I would like to have them separated, e.g. odyssey showing only music files.

**Comment by djselbeck** [comment]
This is not possible at the moment because Odyssey uses the media library provided by the android system and this scans all your folders.

The only way to prevent them from including is by creating a file called .nomedia in a directory.

**Comment by ildar** [comment]
Wait.
You can choose your default directory in "Files" view. Then use Files.
Isn't it enough?

**Comment by github-user-1** [comment]
Unfortunately, not. It seems the Files section is only for looking at files - one can select a standard folder and scan for files there, but that doesn't affect the audio files listed. Odyssey always shows all audio files on my phone.

**Comment by ildar** [comment]
Then as suggested, mark podcast folders with ".nomedia". Alright?

**Comment by github-user-1** [comment]
This is also no solution as then the other apps like (audio-recorder, audio-book-player, podcasts, etc.) don't work (they ignore these folders as well then). As far as I understand the solution is (like in other apps) to provide an option to select the folders where to search for music files. VLC has the option but isn't maintained on F-Droid unfortunately.

**Comment by djselbeck** [comment]
VLC is using its own metadata database and not the one provided by android. We would like to have this sometime in the future but at the moment we just don't have the time to implement this.

**Comment by gnome17** [comment]
Hi,
as mentioned in #30 your only option for the moment is to group your audio files in the system default folders like Podcasts. 

For example:
This means that the Media library of Android detects podcasts if they are in the Podcasts folder inside the internal sd (/storage/emulated/0/Podcasts for me) or the external SD card (/storage/SOME-UUID/Podcasts).

Unfortunately as far as I know Android doesn't provide foldes for audiobooks and recordings but maybe you could place all these audiofiles in the system podcast folder?

It may be also worth mentioning that the selection of a standard folder only controls the default folder that is opened when you open the files tab in odyssey. This option has nothing todo with the other parts of the app. And the option to scan a folder is only a convience method to add music to the media library without restarting your device.

**Comment by snaunton** [comment]
Just to add to gnome17s's comment above.

If you also want to remove custom ringtones from Odyssey (which is what lead me here in addition to removing podcasts), the ringtones (appear to) need to be .ogg format and in /storage/emulated/0/Ringtones.

**Comment by privacy-wolf** [comment]
It's a pitty that this will not become availabe for odyssey since I really like the look-and-feel of it. I use VLC (which offers custom folders only for audio folders) and probably stick to if then. Good luck with odyssey!
