### ISSUE TITLE
Add the option of using the embedded album image of the file

### ISSUE THREAD

**Issue by k2arim99** [gateship-one/odyssey#90]
i have a ton of music that has its high quality cover art embedded and in odyssey they look choppy and compressed cheers

**Comment by gnome17** [comment]
Hi,
odyssey will always prefer an image stored in the media database. Did your images appear in other music apps that use the android media database to retrieve the images?
Another option is to deactivate the cover art download in the settings of odyssey and clear the cover database and check if the problem still appears.

**Comment by k2arim99** [comment]
i had already disabled it, and yeah yes for example phonograph uses the media store ones unless you disable it in the options, with makes it read them directly from the media file, so just a quality of life suggestion, is really nifty in some situations such as mine and isnt as resource heavy as i thought and i have a kind of old phone

**Comment by djselbeck** [comment]
We've tested this with an testfile that has an 3840x2160 image embedded and it looks like the android media store is downscaling the images. 

As we currently are not using a tagging library (like taglib) we don't have another solution. Maybe in the distant future.

**Comment by k2arim99** [comment]
i see so a solution like phonograph is not possible?, well hopely someday
