### ISSUE TITLE
Album covers not displaying properly

### ISSUE THREAD

**Issue by RobertCMonahan** [gateship-one/odyssey#91]
some of the album covers only show about half of the artwork and the bottom half is black. 

![screenshot_20170805-075739](https://user-images.githubusercontent.com/7906594/28996005-8802b40e-79b4-11e7-8d3f-a5c143be0705.png)

I haven't seen it happen with any of the generated content it's only covers that are stored locally on the phone.

**Comment by gnome17** [comment]
Hi,
I am not sure what you mean with generated content. Could you verify that this happen only with cover arts that are retrieved from the android media database? 
An option to verify this is to deactivate the cover art download in the settings of odyssey and clear the cover database and check if the problem still appears.

Does this problem occur with other music apps that use the android media database?

**Comment by RobertCMonahan** [comment]
I was only happening with covers that were not being retrieved from the media database. I had tried to clear the cover database and it still remained. Most recently, I have reinstalled Odyssey and the problem seems to have gone away. I'm not sure what caused it, but if I see it again I'll do a bit more investigating.

**Comment by gnome17** [comment]
Hi,
we close this for now. If the problem reoccurs please open another issue and reference this one.
