### ISSUE TITLE
Songs on the "Tracks" view should continue/cue the rest of the track-list, rather then just stopping at the end.

### ISSUE THREAD

**Issue by zayuim** [gateship-one/odyssey#93]
Right now when selecting a song from the track view instead of moving to the next track on the track view, The song will just stop.

I believe that when playing songs from the "Tracks" view it should either cue the rest of the list or have some sort of script to play the next song.

**Comment by ildar** [comment]
Excuse my curiosity, why would you want the half of your phonoteque in your
playlist? That's just exceeds my understanding... and imagination.

**Comment by zayuim** [comment]
@ildar Most music players will automatically move onto the next song. Except with Odyssey it will only work with albums but not the 'tracks' view. Adding all of it to the playlist would be a way to have that behavior, not ideal though.

**Comment by djselbeck** [comment]
It is intended because I have around 25000 songs on my phone and don't want them all enqueued at once. For reasons of time from click to playback and because it is unhandy.
