### ISSUE TITLE
Search in Files view needs related actions

### ISSUE THREAD

**Issue by ildar** [gateship-one/odyssey#94]
It is great we have Search in the current folder. But it needs actions.
E.g. I have many files in "kahvi.org" folder. I tap Search and enter e.g. "kolibri" (artist's name) and see all his tracks. But I cannot just tap Play to play the search result.
Play button plays the whole folder, not the search result. Counterintuitive.

**Comment by gnome17** [comment]
This bug is fixed in version 1.1.7. It is already available at Google Play and will be available on F-Droid in the next few days we think.
