### ISSUE TITLE
[FR] Hide albums

### ISSUE THREAD

**Issue by Allen-B1** [gateship-one/odyssey#96]
I'd like to be able to hide albums

**Comment by ildar** [comment]
That's quite easy: in your favorite file manager get to the album's folder
and create file `.nomedia` there. After Android updates the folder contents
(e.g. on reboot), the album gets hidden.
The best suited FM would be the CyanogenMod's old FM (
https://f-droid.org/archive/com.cyanogenmod.filemanager.ics_1015.apk)

**Comment by Allen-B1** [comment]
Alright, thanks. Is there a way to do this from the user interface?

**Comment by gnome17** [comment]
Duplicate see #87
